### ISSUE TITLE
Add posibility to set release and next development version

### ISSUE THREAD

**Issue by Befrish** [qcastel/github-actions-maven-release#11]
Currently I can see no possibilty to set the release version and development version.

See https://maven.apache.org/maven-release/maven-release-plugin/examples/non-interactive-release.html

This can be used e.q. in a manual github action to do a release.

A workaround can be writing a properties file (_release.properties_).

**Comment by qcastel** [comment]
Hello @Befrish ,

Today, I implemented the following feature https://github.com/qcastel/github-actions-maven-release#increase-major-or-minor-version
This should simplify the increment of the versioning.

if just incrementing the major and minor version is not enough, you can still use the maven options directly.
https://github.com/qcastel/github-actions-maven-release#adding-maven-options
From the examples on the link you quoted, this would look like that:

```
        with:
            maven-options: "-Dtag=my-proj-1.2 -DreleaseVersion=1.2 -DdevelopmentVersion=2.0-SNAPSHOT"
```

let me know if you still have issues customising the versioning.
