### ISSUE TITLE
Permission denied after new version of action

### ISSUE THREAD

**Issue by dbelob** [qcastel/github-actions-maven-release#14]
Yesterday's release of a new version of the action broke the builds in my two public repositories:

    Agent pid 9
    Do a SSH add with the key under env 'SSH_PRIVATE_KEY'
    Set StrictHostKeyChecking no
    # github.com:22 SSH-2.0-babeld-17f526ba
    # gitlab.com:22 SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.8
    # bitbucket.org:22 SSH-2.0-conker_b9a79bcd5e-dirty conker-3000
    Cloning into 'idhub-api'...
    load pubkey "/root/.ssh/id_rsa": invalid format
    Warning: Permanently added the RSA host key for IP address '140.82.114.3' to the list of known hosts.
    Load key "/root/.ssh/id_rsa": invalid format
    git@github.com: Permission denied (publickey).
    fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.
    Git clone failed

Action of my first repository (GITHUB_TOKEN standard token is used):

    - name: Release with Maven
      uses: qcastel/github-actions-maven-release@master
      with:
        release-branch-name: "master"
        maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip"
        git-release-bot-name: "release-bot"
        git-release-bot-email: "release-bot@github.com"
        access-token: ${{ secrets.GITHUB_TOKEN }}
        skip-perform: true

Action of my second repository (RELEASE_TOKEN personal access token is used for branch with protection rules):

    - name: Release with Maven
      uses: qcastel/github-actions-maven-release@master
      with:
        release-branch-name: "master"
        maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip"
        git-release-bot-name: "release-bot"
        git-release-bot-email: "release-bot@github.com"
        access-token: ${{ secrets.RELEASE_TOKEN }}
        skip-perform: true

Scopes of RELEASE_TOKEN personal access token:
![Screenshot - 13 11 2020 , 12_07_40](https://user-images.githubusercontent.com/22131253/99051916-97b73880-25a9-11eb-8f9d-44c4abc885ab.png)

I can write links to my repositories and provide additional information (if required).

**Comment by qcastel** [comment]
Hello @dbelob,

Indeed, seems I did a few mistake yesterday during my release of the new version of this github action.
Just fix it.
Before we close this one, would you mind verifying it's all good on your side?

Btw I can see you are playing with tokens and I find it quite boiler plate compare to SSH. Perhaps you may be interested to switch to SSH keys:
https://github.com/qcastel/github-actions-maven-release/#setup-with-ssh

**Comment by dbelob** [comment]
I have restarted (**Re-run all jobs** command in menu) action in both repositories: failure, same (for both repositories) errors:

    ##[group]Run qcastel/github-actions-maven-release@master
    with:
      release-branch-name: master
      maven-args: -Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip
      git-release-bot-name: release-bot
      git-release-bot-email: release-bot@github.com
      access-token: ***
      skip-perform: true
      gpg-enabled: false
      maven-project-folder: ./
      version-major: false
      version-minor: false
      m2-home-folder: /root/.m2
    env:
      JAVA_HOME_8.0.275_x64: /opt/hostedtoolcache/jdk/8.0.275/x64
      JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.275/x64
      JAVA_HOME_8_0_275_X64: /opt/hostedtoolcache/jdk/8.0.275/x64
    ##[endgroup]
    ##[command]/usr/bin/docker run --name bb10b6331e6675194c5aab3e8c964fc3d816_46a4cf --label 54bb10 --workdir /github/workspace --rm -e JAVA_HOME_8.0.275_x64 -e JAVA_HOME -e JAVA_HOME_8_0_275_X64 -e INPUT_RELEASE-BRANCH-NAME -e INPUT_MAVEN-ARGS -e INPUT_GIT-RELEASE-BOT-NAME -e INPUT_GIT-RELEASE-BOT-EMAIL -e INPUT_ACCESS-TOKEN -e INPUT_SKIP-PERFORM -e INPUT_GPG-ENABLED -e INPUT_GPG-KEY-ID -e INPUT_GPG-KEY -e INPUT_SSH-PRIVATE-KEY -e INPUT_MAVEN-REPO-SERVER-ID -e INPUT_MAVEN-REPO-SERVER-USERNAME -e INPUT_MAVEN-REPO-SERVER-PASSWORD -e INPUT_MAVEN-PROJECT-FOLDER -e INPUT_MAVEN-OPTIONS -e INPUT_VERSION-MAJOR -e INPUT_VERSION-MINOR -e INPUT_M2-HOME-FOLDER -e GPG_ENABLED -e GPG_KEY_ID -e GPG_KEY -e SSH_PRIVATE_KEY -e SSH_ROOT_FOLDER -e MAVEN_REPO_SERVER_ID -e MAVEN_REPO_SERVER_USERNAME -e MAVEN_REPO_SERVER_PASSWORD -e MAVEN_PROJECT_FOLDER -e MAVEN_ARGS -e MAVEN_OPTION -e M2_HOME_FOLDER -e GIT_RELEASE_BOT_NAME -e GIT_RELEASE_BOT_EMAIL -e SKIP_PERFORM -e GITHUB_ACCESS_TOKEN -e VERSION_MAJOR -e VERSION_MINOR -e RELEASE_BRANCH_NAME -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/twitter-emulation/twitter-emulation":"/github/workspace" 54bb10:b6331e6675194c5aab3e8c964fc3d816  "release-github-actions.sh"
    Last release-bot commit: 
    Current commit: a9c9f088c2223d843510fe12bfc850ca7bfea4a1
    Current branch: master
    Using SSH folder /github/home/.ssh
    Using M2 repository folder /root/.m2
    /root/.m2 is empty, this means we didn't hit a potential M2 cache :(
    Git checkout branch master
    Already on 'master'
    Your branch is up to date with 'origin/master'.
    Git reset hard to a9c9f088c2223d843510fe12bfc850ca7bfea4a1
    HEAD is now at a9c9f08 Merge pull request #212 from dbelob/dependabot/maven/spring.boot.version-2.4.0
    Setup git user name to 'release-bot'
    Setup git user email to 'release-bot@github.com'
    GPG_ENABLED 'false'
    GPG signing is not enabled
    No SSH key defined
    Move to folder ./
    Do mvn release:prepare with options  and arguments -Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip
    The JAVA_HOME environment variable is not defined correctly
    This environment variable is needed to run this program
    NB: JAVA_HOME should point to a JDK not a JRE

**Comment by qcastel** [comment]
Seems you are overriding the java home

```
env:
 JAVA_HOME_8.0.275_x64: /opt/hostedtoolcache/jdk/8.0.275/x64
 JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.275/x64
 JAVA_HOME_8_0_275_X64: /opt/hostedtoolcache/jdk/8.0.275/x64
```

That's causing an issue as I moved to an alpine base image.

I guess compiling with Java 11 not an option for you. I will see how I can add a feature to choose the JDK version

**Comment by qcastel** [comment]
@dbelob I pushed a new version that contains JDK 8.

Try using this:

```
env:
 JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk/
```

Let me know if you manage to get it working with this change

**Comment by dbelob** [comment]
Successfully for first repository, because first application uses _JDK 8_.

My full job files for two applications: [jobs.zip](https://github.com/qcastel/github-actions-maven-release/files/5538147/jobs.zip)

Full current action description for first application:

    - name: Release with Maven
      uses: qcastel/github-actions-maven-release@master
      with:
        release-branch-name: "master"
        maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip"
        git-release-bot-name: "release-bot"
        git-release-bot-email: "release-bot@github.com"
        access-token: ${{ secrets.GITHUB_TOKEN }}
        skip-perform: true
      env:
        JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk/

> Seems you are overriding the java home

I use _JDK 11_ in second application (see **actions/setup-java@v1** action). I cannot compile the second application now:

    ##[group]Run qcastel/github-actions-maven-release@master
    with:
      release-branch-name: master
      maven-args: -Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip
      git-release-bot-name: release-bot
      git-release-bot-email: release-bot@github.com
      access-token: ***
      skip-perform: true
      gpg-enabled: false
      maven-project-folder: ./
      version-major: false
      version-minor: false
      m2-home-folder: /root/.m2
    env:
      JAVA_HOME_11.0.9_x64: /opt/hostedtoolcache/jdk/11.0.9/x64
      JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk/
      JAVA_HOME_11_0_9_X64: /opt/hostedtoolcache/jdk/11.0.9/x64
    ##[endgroup]
    ##[command]/usr/bin/docker run --name bb1096e720ace65d42b295d1895d79e3a424_34a066 --label 54bb10 --workdir /github/workspace --rm -e JAVA_HOME_11.0.9_x64 -e JAVA_HOME -e JAVA_HOME_11_0_9_X64 -e INPUT_RELEASE-BRANCH-NAME -e INPUT_MAVEN-ARGS -e INPUT_GIT-RELEASE-BOT-NAME -e INPUT_GIT-RELEASE-BOT-EMAIL -e INPUT_ACCESS-TOKEN -e INPUT_SKIP-PERFORM -e INPUT_GPG-ENABLED -e INPUT_GPG-KEY-ID -e INPUT_GPG-KEY -e INPUT_SSH-PRIVATE-KEY -e INPUT_MAVEN-REPO-SERVER-ID -e INPUT_MAVEN-REPO-SERVER-USERNAME -e INPUT_MAVEN-REPO-SERVER-PASSWORD -e INPUT_MAVEN-PROJECT-FOLDER -e INPUT_MAVEN-OPTIONS -e INPUT_VERSION-MAJOR -e INPUT_VERSION-MINOR -e INPUT_M2-HOME-FOLDER -e GPG_ENABLED -e GPG_KEY_ID -e GPG_KEY -e SSH_PRIVATE_KEY -e SSH_ROOT_FOLDER -e MAVEN_REPO_SERVER_ID -e MAVEN_REPO_SERVER_USERNAME -e MAVEN_REPO_SERVER_PASSWORD -e MAVEN_PROJECT_FOLDER -e MAVEN_ARGS -e MAVEN_OPTION -e M2_HOME_FOLDER -e GIT_RELEASE_BOT_NAME -e GIT_RELEASE_BOT_EMAIL -e SKIP_PERFORM -e GITHUB_ACCESS_TOKEN -e VERSION_MAJOR -e VERSION_MINOR -e RELEASE_BRANCH_NAME -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/guess-game/guess-game":"/github/workspace" 54bb10:96e720ace65d42b295d1895d79e3a424  "release-github-actions.sh"
    Last release-bot commit: 
    Current commit: 0118416520266e81069391a41f3b7c13aa3c9ac9
    Current branch: master
    Using SSH folder /github/home/.ssh
    Using M2 repository folder /root/.m2
    /root/.m2 is empty, this means we didn't hit a potential M2 cache :(
    Git checkout branch master
    Already on 'master'
    Your branch is up to date with 'origin/master'.
    Git reset hard to 0118416520266e81069391a41f3b7c13aa3c9ac9
    HEAD is now at 0118416 Merge pull request #201 from JugruGroup/fix-deploy
    Setup git *** name to 'release-bot'
    Setup git *** email to 'release-bot@github.com'
    GPG_ENABLED 'false'
    GPG signing is not enabled
    No SSH key defined
    Move to folder ./
    Do mvn release:prepare with options  and arguments -Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip
    16:42:28,202 [INFO] Scanning for projects...
    ...
    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project guess-game-server: Fatal error compiling: invalid target release: 11 -> [Help 1]

**Comment by qcastel** [comment]
@dbelob seems you setup the env for both of your projects but as you got one in JDK11, only apply:

```
env:
 JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk/
```

to your Java 8 app. For the other, don't setup this variable as by default, it will use JDK 11

**Comment by dbelob** [comment]
Both applications use _JDK 11_ now.

Full job file of first application:

    name: Deploy
    
    on:
      push:
        branches: [ master ]
    
    jobs:
      deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Set up JDK
            uses: actions/setup-java@v1
            with:
              java-version: 11
          - name: Cache Maven packages
            uses: actions/cache@v2
            with:
              path: ~/.m2
              key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
              restore-keys: ${{ runner.os }}-m2
          - name: Release with Maven
            uses: qcastel/github-actions-maven-release@master
            with:
              release-branch-name: "master"
              maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip"
              git-release-bot-name: "release-bot"
              git-release-bot-email: "release-bot@github.com"
              access-token: ${{ secrets.GITHUB_TOKEN }}
              skip-perform: true

Error log:

    ##[group]Run qcastel/github-actions-maven-release@master
    with:
      release-branch-name: master
      maven-args: -Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip
      git-release-bot-name: release-bot
      git-release-bot-email: release-bot@github.com
      access-token: ***
      skip-perform: true
      gpg-enabled: false
      maven-project-folder: ./
      version-major: false
     version-minor: false
      m2-home-folder: /root/.m2
    env:
      JAVA_HOME_11.0.9_x64: /opt/hostedtoolcache/jdk/11.0.9/x64
      JAVA_HOME: /opt/hostedtoolcache/jdk/11.0.9/x64
     JAVA_HOME_11_0_9_X64: /opt/hostedtoolcache/jdk/11.0.9/x64
    ##[endgroup]
    ##[command]/usr/bin/docker run --name bb10419dca58a3334fb6a73649aa401a32c2_c580da --label 54bb10 --workdir /github/workspace --rm -e JAVA_HOME_11.0.9_x64 -e JAVA_HOME -e JAVA_HOME_11_0_9_X64 -e INPUT_RELEASE-BRANCH-NAME -e INPUT_MAVEN-ARGS -e INPUT_GIT-RELEASE-BOT-NAME -e INPUT_GIT-RELEASE-BOT-EMAIL -e INPUT_ACCESS-TOKEN -e INPUT_SKIP-PERFORM -e INPUT_GPG-ENABLED -e INPUT_GPG-KEY-ID -e INPUT_GPG-KEY -e INPUT_SSH-PRIVATE-KEY -e INPUT_MAVEN-REPO-SERVER-ID -e INPUT_MAVEN-REPO-SERVER-USERNAME -e INPUT_MAVEN-REPO-SERVER-PASSWORD -e INPUT_MAVEN-PROJECT-FOLDER -e INPUT_MAVEN-OPTIONS -e INPUT_VERSION-MAJOR -e INPUT_VERSION-MINOR -e INPUT_M2-HOME-FOLDER -e GPG_ENABLED -e GPG_KEY_ID -e GPG_KEY -e SSH_PRIVATE_KEY -e SSH_ROOT_FOLDER -e MAVEN_REPO_SERVER_ID -e MAVEN_REPO_SERVER_USERNAME -e MAVEN_REPO_SERVER_PASSWORD -e MAVEN_PROJECT_FOLDER -e MAVEN_ARGS -e MAVEN_OPTION -e M2_HOME_FOLDER -e GIT_RELEASE_BOT_NAME -e GIT_RELEASE_BOT_EMAIL -e SKIP_PERFORM -e GITHUB_ACCESS_TOKEN -e VERSION_MAJOR -e VERSION_MINOR -e RELEASE_BRANCH_NAME -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/twitter-emulation/twitter-emulation":"/github/workspace" 54bb10:419dca58a3334fb6a73649aa401a32c2  "release-github-actions.sh"
    Last release-bot commit: 
    Current commit: 3f15f6afb55d12d381ab874630f2fc28eb26b626
    Current branch: master
    Using SSH folder /root/.ssh
    Using M2 repository folder /root/.m2
    /root/.m2 is empty, this means we didn't hit a potential M2 cache :(
    Git checkout branch master
    Already on 'master'
    Your branch is up to date with 'origin/master'.
    Git reset hard to 3f15f6afb55d12d381ab874630f2fc28eb26b626
    HEAD is now at 3f15f6a Merge pull request #217 from dbelob/fix-deploy
    Setup git user name to 'release-bot'
    Setup git user email to 'release-bot@github.com'
    GPG_ENABLED 'false'
    GPG signing is not enabled
    No SSH key defined
    Move to folder ./
    Do mvn release:prepare with options  and arguments -Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip
    The JAVA_HOME environment variable is not defined correctly
    This environment variable is needed to run this program
    NB: JAVA_HOME should point to a JDK not a JRE

I created a minimal project to reproduce error, see [dbelob/github-actions-maven-release-error](https://github.com/dbelob/github-actions-maven-release-error) repository. See **Actions** tab with [Deploy job errors](https://github.com/dbelob/github-actions-maven-release-error/actions).

**Comment by qcastel** [comment]
Try removing 

```
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
```
This github action seems to override the JAVA home but it's giving crap info. It's assuming you would compile using the github official maven compile, which is not your case.

**Comment by dbelob** [comment]
I removed

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11

in both applications.

The bugs disappeared for the first application, but remained for the second (see the next comment for details).

I looked at the code [qcastel/github-actions-maven-release](https://github.com/qcastel/github-actions-maven-release) and [qcastel/docker-maven-release](https://github.com/qcastel/docker-maven-release).

I realized that the **github-actions-maven-release** action is being executed in a docker container (alpine:3) with additional **openjdk11**, **openjdk8**, etc. packages installed. **openjdk8** package was added by [commit](https://github.com/qcastel/docker-maven-release/commit/6c03fdcce0394012aa66b4296840f9c9652bef1d#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557) 2 days ago. We cannot set an environment variable before calling the action, because it will be transferred to the container when the docker starts.

I suppose that
1. No need to add **openjdk8** package to image. The **openjdk11** package is sufficient.
2. The **openjdk11** package ensures that applications are compiled only for _Java 11_ and earlier. I cannot use Java 12, 13, etc. in my application and use the **github-actions-maven-release** action.

Are my assumptions correct?

(Now I will write in detail the following message about the remaining error in the second application)

**Comment by qcastel** [comment]
@dbelob I installed JDK 8 for you the other day. 

1. In certain case, some Java 8 applications don't compile with JDK 11. This is why installed JDK 8 as well, in case you are in this situation.

2. Indeed, only Java 11 is supported here. As Java 11 is the latest LTE version, that would be my recommendation anyway to not use JDK12+ in production system. although if someone insisted, I would accept installing JDK 12+, just wouldn't make them default for this github action.

Indeed, your code investigation is correct, this github action uses a dedicated docker image that I build for making the release. Setting up environment variables in a previous git action is not recommended, as this assume they will be ran under the same container, which won't be the case.
My reasoning behind using a dedicated docker image, is as follow:
- Consistant build even if github changes their default base image
- Easily reproduce-able outside github: you pull the image, you can reproduce the same behaviour locally.
- Using the release image, called 'docker-maven-release', in other CI tool. Simplifying the migration of a repository from github to gitlab for example. Personally, I uses this docker image in all my java projects, gitlab, github, bitbucket.

**Comment by dbelob** [comment]
My second application has **master** branch with protection rules:
![Screenshot - 15 11 2020 , 15_14_24](https://user-images.githubusercontent.com/22131253/99187173-148f1180-2766-11eb-9241-4be36ffcd06c.png)

In order to be able to perform an action for such a branch, GITHUB_TOKEN token is not enough. Personal access token created with scopes:
![Screenshot - 13 11 2020 , 12_07_40](https://user-images.githubusercontent.com/22131253/99187717-49e92e80-2769-11eb-8a99-85490616f285.png)

In application RELEASE_TOKEN secret added with value from personal access token.

Full job description:

    name: Deploy
    
    on:
      push:
        branches: [ master ]
    
    jobs:
      deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
            with:
              persist-credentials: false
          - name: Cache Maven packages
            uses: actions/cache@v2
            with:
              path: ~/.m2
              key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
              restore-keys: ${{ runner.os }}-m2
          - name: Release with Maven
            uses: qcastel/github-actions-maven-release@master
            with:
              release-branch-name: "master"
              maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip"
              git-release-bot-name: "release-bot"
              git-release-bot-email: "release-bot@github.com"
              access-token: ${{ secrets.RELEASE_TOKEN }}
              skip-perform: true

Attention: using strings

            with:
              persist-credentials: false

is mandatory!

In the previous version of the **github-actions-maven-release** action, everything worked (only with RELEASE_TOKEN and `persist-credentials: false`).

Errors in the new version:

    ##[group]Run qcastel/github-actions-maven-release@master
    with:
      release-branch-name: master
      maven-args: -Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip
      git-release-bot-name: release-bot
      git-release-bot-email: release-bot@github.com
      access-token: ***
      skip-perform: true
      gpg-enabled: false
      maven-project-folder: ./
      version-major: false
      version-minor: false
      m2-home-folder: /root/.m2
    ##[endgroup]
    ##[command]/usr/bin/docker run --name bb1076b0b91bfe434aea85e57b0e3ef3297d_d815d2 --label 54bb10 --workdir /github/workspace --rm -e INPUT_RELEASE-BRANCH-NAME -e INPUT_MAVEN-ARGS -e INPUT_GIT-RELEASE-BOT-NAME -e INPUT_GIT-RELEASE-BOT-EMAIL -e INPUT_ACCESS-TOKEN -e INPUT_SKIP-PERFORM -e INPUT_GPG-ENABLED -e INPUT_GPG-KEY-ID -e INPUT_GPG-KEY -e INPUT_SSH-PRIVATE-KEY -e INPUT_MAVEN-REPO-SERVER-ID -e INPUT_MAVEN-REPO-SERVER-USERNAME -e INPUT_MAVEN-REPO-SERVER-PASSWORD -e INPUT_MAVEN-PROJECT-FOLDER -e INPUT_MAVEN-OPTIONS -e INPUT_VERSION-MAJOR -e INPUT_VERSION-MINOR -e INPUT_M2-HOME-FOLDER -e GPG_ENABLED -e GPG_KEY_ID -e GPG_KEY -e SSH_PRIVATE_KEY -e SSH_ROOT_FOLDER -e MAVEN_REPO_SERVER_ID -e MAVEN_REPO_SERVER_USERNAME -e MAVEN_REPO_SERVER_PASSWORD -e MAVEN_PROJECT_FOLDER -e MAVEN_ARGS -e MAVEN_OPTION -e M2_HOME_FOLDER -e GIT_RELEASE_BOT_NAME -e GIT_RELEASE_BOT_EMAIL -e SKIP_PERFORM -e GITHUB_ACCESS_TOKEN -e VERSION_MAJOR -e VERSION_MINOR -e RELEASE_BRANCH_NAME -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/github-actions-maven-release-error/github-actions-maven-release-error":"/github/workspace" 54bb10:76b0b91bfe434aea85e57b0e3ef3297d  "release-github-actions.sh"
    ...
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time:  14.897 s
    [INFO] Finished at: 2020-11-15T13:16:38Z
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project github-actions-maven-release-error: Unable to commit files
    [ERROR] Provider message:
    [ERROR] The git-push command failed.
    [ERROR] Command output:
    [ERROR] fatal: could not read Username for 'https://github.com': No such device or address
    [ERROR] -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

See  [dbelob/github-actions-maven-release-error](https://github.com/dbelob/github-actions-maven-release-error) project (I change it) and [errors in the Actions tab](https://github.com/dbelob/github-actions-maven-release-error/actions) (for **Deploy** job).

Please help.

**Comment by dbelob** [comment]
Congratulation! After your changes, the errors disappeared in all applications (in my test and real).

I have two suggestions, see #15

**Comment by qcastel** [comment]
Thanks @dbelob for your patiences in trying my latest github actions. We nailed it at the end :)

**Comment by dbelob** [comment]
> Thanks @dbelob for your patiences in trying my latest github actions. We nailed it at the end :)

Thanks for the excellent actions for GitHub Actions!

**Comment by dbelob** [comment]
@qcastel Sorry, I am temporarily forced to stop sponsorship.

I can't transfer money with credit cards outside the country due to Russia's invasion of Ukraine:
- Visa and Mastercard block all transfers from Russia;
- Russian government banned the transfer of currency electronically with the threat of criminal prosecution.

I will resume sponsorship after the unblocking of money transfers from Russia.

**Comment by qcastel** [comment]
Hello @dbelob

Thanks for sponsoring me for all those months already. Let's all hope this war will be over soon
