### ISSUE TITLE
Versioning of action

### ISSUE THREAD

**Issue by dbelob** [qcastel/github-actions-maven-release#15]
Please consider adding versioning to your **github-actions-maven-release** action (and others too).

That is, instead of using

    uses: qcastel/github-actions-maven-release@master

to use

    uses: qcastel/github-actions-maven-release@v1

for version 1,

    uses: qcastel/github-actions-maven-release@v2

for version 2 etc.

This practice will help to avoid the consequences of possible errors in the new version with significant changes in functionality. For example, on errors in version v2, I could temporarily continue to use v1 (see #14).

You write wonderful useful applications. I suggest giving [GitHub Sponsors](https://docs.github.com/en/free-pro-team@latest/github/supporting-the-open-source-community-with-github-sponsors/setting-up-github-sponsors-for-your-user-account) a try. I am ready to sponsor your projects.

**Comment by qcastel** [comment]
@dbelob It's already versioned, I created tags in a regular basis:

https://github.com/qcastel/github-actions-maven-release/tags

The recent changes that are made were indeed braking the API, I therefore moved from 1.11.x to 1.12.x.

**Comment by qcastel** [comment]
Despite I do versioning, there is a security risk in the current design of the github actions. It is explained here: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
`Pin actions to a full length commit SHA`

I would recommend following this security recommendation if you are using github actions for producing artefact designed to be consumed on a production environment.

**Comment by dbelob** [comment]
Other actions have version number in name. For example, **codecov/codecov-action@v1**

> The recent changes that are made were indeed braking the API, I therefore moved from 1.11.x to 1.12.x.

Could this somehow help me when an error appears in **qcastel/github-actions-maven-release@master**?

Was I able to switch to a previous working version?

**Comment by qcastel** [comment]
After the '@' is a commit reference. You can therefore use 

`qcastel/github-actions-maven-release@1.12.1` 

> Was I able to switch to a previous working version?

Yes, you could have done that. You could have moved to `qcastel/github-actions-maven-release@v1.11.2`

**Comment by dbelob** [comment]
> Yes, you could have done that. You could have moved to `qcastel/github-actions-maven-release@v1.11.2`

Now I know about it, thanks.

> but if you did, you wouldn't contribute to this github actions by bulletproofing the latest version. For that, I thank you.

If this situation occurs again, I will use the old version number temporarily and create an issue.

Please think about GitHub Sponsors :)

**Comment by dbelob** [comment]
The ability to specify versions exists (for example, `qcastel/github-actions-maven-release@v1.11.2`).

**Comment by qcastel** [comment]
> You write wonderful useful applications. I suggest giving GitHub Sponsors a try. I am ready to sponsor your projects.


I never really knew or even thought about github sponsor. Thanks for the suggestion, I will give it a go out of curiosity of out this work!

**Comment by qcastel** [comment]
As a followup of this RFE, I extended the readme to highlight how versioning can we used on this github action: https://github.com/qcastel/github-actions-maven-release#choose-your-version-of-this-github-action

**Comment by qcastel** [comment]
@dbelob here you go, I am now in github sponsors program! :)  https://github.com/sponsors/qcastel

**Comment by dbelob** [comment]
> @dbelob here you go, I am now in github sponsors program! :) https://github.com/sponsors/qcastel

Already.

**Comment by qcastel** [comment]
Many thanks! Will use your contribution in my next project, will mention @ you the repo once it's live :)
