### ISSUE TITLE
Maven-Release skipping all branches?

### ISSUE THREAD

**Issue by Craftoncu** [qcastel/github-actions-maven-release#19]
Hey!
I just tried your GitHub tool for releasing my artifacts to the github repo.

But I get always the same message:

Last release-bot commit: 
Current commit: e1aadd78eac622819b19f7c1bb89798345be3b7a
Current branch: main
Skipping for main branch

Version latest
Connection ssh

**Comment by qcastel** [comment]
Hello @Craftoncu ,

I am still a fan of using "master" as the default branch and so is the github action at the end.
If you want to switch to a different release branch, have a look at: 
https://github.com/qcastel/github-actions-maven-release#customise-the-default-branch

In your case, you want:

```
 with:
            release-branch-name: "main"
```
