### ISSUE TITLE
Add option for a subdirectory

### ISSUE THREAD

**Issue by Turbots** [qcastel/github-actions-maven-release#2]
I have a repository containing more than one Maven project.

Would be great if you could add a working directory or "subdirectory" option to run the `mvn release` command from

**Comment by qcastel** [comment]
Hello @Turbots 

I was fixing a bug in this github action and decided to implement your feature request at the same time. 
You can now specified the sub folder using the option
```
maven-project-folder: "./your_folder"
```
I added this in the readme as well.

Enjoy!
