### ISSUE TITLE
README typo - version increment

### ISSUE THREAD

**Issue by awhitford** [qcastel/github-actions-maven-release#21]
Here:  https://github.com/marketplace/actions/maven-release#increase-major-or-minor-version

> By default, maven release will increase the path version.

I think you mean to say, "_patch_ version."

**Comment by qcastel** [comment]
Yes, thats a typo, I meant patch.

Thanks for raising issues for helping getting this documentation more clear to everyone, much appreciate!

**Comment by awhitford** [comment]
There were 2 cases of `path` instead of `patch`.  Please see:  https://github.com/qcastel/github-actions-maven-release#features

> Increment the major or minor version (by default, it's the path version that is increased)

**Comment by qcastel** [comment]
It's fixed too. thanks for checking my back! 


Btw today I release an article on medium to show how to use this github actions using a sample app as demo:
https://quentincastel86.medium.com/release-your-maven-project-using-github-actions-51beba1e4834
That may interest you if you are exploring the usage of this github action
