### ISSUE TITLE
Please explain why you may not release from your master branch.

### ISSUE THREAD

**Issue by awhitford** [qcastel/github-actions-maven-release#22]
From:  https://github.com/marketplace/actions/maven-release#customise-the-default-branch

> You may not release from your master branch.

Can you please explain this?  (I am releasing from the master branch now, so why does this action have such a restriction?)

**Comment by qcastel** [comment]
My bad, it's indeed not very clear at all.
I reviewed and hopefully its more explicit this time: https://github.com/qcastel/github-actions-maven-release/blob/master/README.md#customise-the-default-branch
