### ISSUE TITLE
Upgrade Checkout

### ISSUE THREAD

**Issue by awhitford** [qcastel/github-actions-maven-release#23]
https://github.com/qcastel/github-actions-maven-release/blob/8db2f7e711f53486d5397fa97262add04a098473/.github/workflows/release.yml#L14

Why not use `checkout@v2`?

**Comment by qcastel** [comment]
No real reason, probably been using github actions for too long that I took the habits of using V1 :) 

I upgraded to V2 and looks good.

Thanks for the heads up!
