### ISSUE TITLE
Set JAVA_HOME default to /usr/lib/jvm/java-1.8-openjdk/ ?

### ISSUE THREAD

**Issue by marwin1991** [qcastel/github-actions-maven-release#29]
Using this plugin cause a error:

```
Error: 1,565 [INFO] 13:25:11,563 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.2.0:jar (attach-javadocs) on project keep-changelog-maven-plugin: MavenReportException: Error while generating Javadoc: Unable to find javadoc command: The environment variable JAVA_HOME is not correctly set. -> [Help 1]
Error: 1,567 [INFO] 13:25:11,566 [ERROR] 

```

Maybe default JAVA_HOME should be set, to lower erros and entry level (connected with #28 - high entry level for this action)

**Comment by qcastel** [comment]
I am not sure to follow you @marwin1991 , are you using this option and it's still not working? https://github.com/qcastel/github-actions-maven-release#sample-repository

**Comment by marwin1991** [comment]
No, when I have added it everything wokred fine, but i thougth there is some default

**Comment by qcastel** [comment]
Currently Java 11 is the default version as it's the current LTS version.

Glad to here that it is now working for you!
