### ISSUE TITLE
Unable to complete run-preparation-goals

### ISSUE THREAD

**Issue by francis-pang** [qcastel/github-actions-maven-release#3]
Hi, I have an issue completing the mvn prepare step
From my [execution log](https://pipelines.actions.githubusercontent.com/gF8rCAbduHaWMSVwUmzuKaU3BSe3Cbkt6iNV5i0sE6qmWpsYYD/_apis/pipelines/1/runs/38/signedlogcontent/5?urlExpires=2020-06-14T15%3A22%3A49.9033008Z&urlSigningMethod=HMACV1&urlSignature=oiohGwXZ0amgovedfLFL8d%2Bun1tocJmDiQ7EXZnBQ50%3D) 

> 2020-06-14T15:21:37.5588455Z [INFO] [prepare] 10/17 run-preparation-goals
> 2020-06-14T15:21:37.5628454Z [INFO] Executing goals 'clean verify'...
> 2020-06-14T15:21:38.9297359Z [INFO] [ERROR] Error executing Maven.
> 2020-06-14T15:21:38.9404496Z [INFO] [ERROR] 1 problem was encountered while building the effective settings
> 2020-06-14T15:21:38.9516804Z [INFO] [ERROR] 'servers.server[0].id' is missing @ /tmp/release-settings10360263975628843972.xml

I believe the container has some tmp folder issue.

**Comment by qcastel** [comment]
Hello @francis-pang 

It sounds like your maven is having a trouble with the custom settings.xml I did.
See https://github.com/qcastel/github-actions-maven-release/blob/master/settings.xml

Sounds like it's not working well if you don't have a maven repo setup.
Will have a look. 

Perhaps try setup MAVEN_REPO_SERVER_ID and see what happen

**Comment by qcastel** [comment]
It's now fixed anyway. Just pushed a commit for it. You can use master or v1.9.1+ :)
