### ISSUE TITLE
Support for JDK 14

### ISSUE THREAD

**Issue by francis-pang** [qcastel/github-actions-maven-release#4]
https://github.com/francis-pang/expense-tally/runs/792821316?check_suite_focus=true

> [INFO] [INFO] BUILD FAILURE
> [INFO] [INFO] ------------------------------------------------------------------------
> [INFO] [INFO] Total time:  16.961 s
> [INFO] [INFO] Finished at: 2020-06-21T15:44:29Z
> [INFO] [INFO] ------------------------------------------------------------------------
> [INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project expense-tally: Fatal error compiling: error: release version 14 not supported -> [Help 1]
> [INFO] [ERROR] 
> [INFO] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [INFO] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [INFO] [ERROR] 
> [INFO] [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [INFO] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  36.364 s
> [INFO] Finished at: 2020-06-21T15:44:29Z
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:3.0.0-M1:prepare (default-cli) on project expense-tally: Maven execution failed, exit code: '1' -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Hi, I think that JDK 14 is not supported. Can you bump up the support version?

**Comment by qcastel** [comment]
Indeed it was still using JDK 11 underneath. I bumped to JDK 14 now. Let me know if you got any issues with it.

**Comment by francis-pang** [comment]
I don't think the issue is resolved.

https://github.com/francis-pang/expense-tally/runs/794461454?check_suite_focus=true

> Run qcastel/github-actions-maven-release@master
>   with:
>     release-branch-name: master
>     git-release-bot-name: release-bot
>     git-release-bot-email: release-bot@example.com
>     maven-args: -Dmaven.javadoc.skip=true  -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip
>     gpg-enabled: false
>     maven-local-repo-path: $M2_HOME/repository
>     maven-project-folder: ./
>     skip-perform: false
>   env:
>     JAVA_HOME: /opt/hostedtoolcache/jdk/14.0.1/x64
>     JAVA_HOME_14.0.1_x64: /opt/hostedtoolcache/jdk/14.0.1/x64
> /usr/bin/docker run --name c27d3121a198dd123a444c8aabbc65ff955360_0068c0 --label c27d31 --workdir /github/workspace --rm -e JAVA_HOME -e JAVA_HOME_14.0.1_x64 -e INPUT_RELEASE-BRANCH-NAME -e INPUT_GIT-RELEASE-BOT-NAME -e INPUT_GIT-RELEASE-BOT-EMAIL -e INPUT_ACCESS-TOKEN -e INPUT_MAVEN-ARGS -e INPUT_GPG-ENABLED -e INPUT_GPG-KEY-ID -e INPUT_GPG-KEY -e INPUT_MAVEN-LOCAL-REPO-PATH -e INPUT_MAVEN-REPO-SERVER-ID -e INPUT_MAVEN-REPO-SERVER-USERNAME -e INPUT_MAVEN-REPO-SERVER-PASSWORD -e INPUT_MAVEN-PROJECT-FOLDER -e INPUT_SKIP-PERFORM -e RELEASE_BRANCH_NAME -e GPG_ENABLED -e GPG_KEY_ID -e GPG_KEY -e MAVEN_LOCAL_REPO_PATH -e MAVEN_REPO_SERVER_ID -e MAVEN_REPO_SERVER_USERNAME -e MAVEN_REPO_SERVER_PASSWORD -e MAVEN_PROJECT_FOLDER -e MAVEN_ARGS -e SKIP_PERFORM -e GIT_RELEASE_BOT_NAME -e GIT_RELEASE_BOT_EMAIL -e GITHUB_ACCESS_TOKEN -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_API_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/expense-tally/expense-tally":"/github/workspace" c27d31:21a198dd123a444c8aabbc65ff955360  "release.sh"
> Last release-bot commit: 
> Current commit: 490bbbf3d0a02db9f4584ba0744fcd8a0bc24f57
> Current branch: master
> Git checkout branch master
> Already on 'master'
> Your branch is up to date with 'origin/master'.
> Git reset hard to 490bbbf3d0a02db9f4584ba0744fcd8a0bc24f57
> HEAD is now at 490bbbf Test trigger maven release
> Setup git user name to 'release-bot'
> Setup git user email to 'release-bot@example.com'
> GPG_ENABLED 'false'
> GPG signing is not enabled
> Override the java home as gitactions is seting up the JAVA_HOME env variable
> Move to folder ./
> Do mvn release:prepare with arguments -Dmaven.javadoc.skip=true  -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip
> The JAVA_HOME environment variable is not defined correctly
> This environment variable is needed to run this program
> NB: JAVA_HOME should point to a JDK not a JRE

I believe that the JAVA_HOME is not being defined correctly. I have a JDK set up before though.

**Comment by qcastel** [comment]
Give it a try now, I think it should be fine

**Comment by qcastel** [comment]
Did a release today on another repo using this github actions and it went fine.
Let me know if you still face an issue but I think now it's on track

**Comment by francis-pang** [comment]
I think that the git reading of key is not provided. Is there a specific github credential which I need to provide?

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:3.0.0-M1:prepare (default-cli) on project expense-tally: Unable to commit files
> [ERROR] Provider message:
> [ERROR] The git-push command failed.
> [ERROR] Command output:
> [ERROR] Host key verification failed.
> [ERROR] fatal: Could not read from remote repository.
> [ERROR] 
> [ERROR] Please make sure you have the correct access rights
> [ERROR] and the repository exists.
> [ERROR] -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by qcastel** [comment]
The github action requires an access token with the repo scope. Perhaps you haven't setup the right priviledges when creating your GITHUB_ACCESS_TOKEN token?

<img width="770" alt="Screenshot 2020-06-23 at 05 57 21" src="https://user-images.githubusercontent.com/3748231/85362898-8779c080-b517-11ea-86c0-f777bc78c53f.png">

Also, probably not the root cause but still best to fix:

Your scm is setup to your old repo name:

```
  <scm>
        <connection>scm:git:git@github.com:boyshawn/expense-tally.git</connection>
        <developerConnection>scm:git:git@github.com:boyshawn/expense-tally.git</developerConnection>
        <tag>HEAD</tag>
    </scm>
```

Instead of git@github.com:francis-pang/expense-tally.git

**Comment by francis-pang** [comment]
![GitHub Personal Access Token](https://user-images.githubusercontent.com/1556501/85400919-bf225000-b58b-11ea-910c-93bc3b1c27f2.png)

I believe this is the setting you mention? ⬆️ 

I have updated it but it still doesn't work: https://github.com/francis-pang/expense-tally/runs/799182856

**Comment by francis-pang** [comment]
Hi @qcastel , I wonder if you have test to take a look at this?

**Comment by jlannoy** [comment]
@francis-pang I had the same problem, and I was able to go through it by changing the `developerConnection` property in my `pom.xml`. It was using the `git` protocol, I changed for the `https` one...

More precisely, I changed from :
```<developerConnection>scm:git:git@github.com:zileo-net/logback-logdna.git</developerConnection>```
to : 
```<developerConnection>scm:git:https://github.com/zileo-net/logback-logdna.git</developerConnection>```

**Comment by francis-pang** [comment]
@jlannoy Yes, this works! Finally! After 3 months of waiting!

**Comment by qcastel** [comment]
I installed JDK 14 and 15. You can find a section in the readme for customising the JDK version: https://github.com/qcastel/github-actions-maven-release#jdk-version
