### ISSUE TITLE
Increase patch version automatically

### ISSUE THREAD

**Issue by BernhardFuchs** [qcastel/github-actions-maven-release#44]
The [docs](https://github.com/marketplace/actions/java-maven-release#increase-major-or-minor-version) show how to increase the `version-major` and the `version-minor`.  
Having the same for `version-patch` would also be helpful.

**Comment by qcastel** [comment]
Maven actually increase the patch version by default. Although to be more explicit and consistant across the other option, I improved the doc and introduced a `version-patch`.

Let me know if you find this more clear now

**Comment by BernhardFuchs** [comment]
Ok, that means if both are set to false the incremented version is the patch version.  
Thx for clarifiying this in the docs.
