### ISSUE TITLE
JDK 21 support as default

### ISSUE THREAD

**Issue by dbelob** [qcastel/github-actions-maven-release#54]
Please add support for _JDK 21_ and make it the default version (_JDK 21_ released yesterday).

Now when I try to use _Java 21_ a error message appears:

    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile)
    on project <module name>: Fatal error compiling: error: invalid target release: 21 -> [Help 1]

Thanks for the great GitHub Actions! I remember [my promise](https://github.com/qcastel/github-actions-maven-release/issues/14#issuecomment-1065925146) ;)

**Comment by dbelob** [comment]
> Added support to JDK 21 in https://github.com/qcastel/github-actions-maven-release/releases/tag/v1.12.40

I don't specify JAVA_HOME (I use the default JDK version) - action now completed without error, thanks a lot!

Should JDK 17 be specified as the default JDK version in the [JDK version section](https://github.com/qcastel/github-actions-maven-release#jdk-version)?

**Comment by qcastel** [comment]
Good catch! I updated the doc saying the default JDK is now 21.
