### ISSUE TITLE
handle gpg passphrase from the plugin

### ISSUE THREAD

**Issue by mwiede** [qcastel/github-actions-maven-release#6]
it would be nice to handle the password of gpg key via plugin property.

I even had to provide `maven-args: "-Dgpg.passphrase="` when the key has no password.

How do you solve this?

**Comment by qcastel** [comment]
Hello @mwiede ,

If you look line https://github.com/qcastel/github-actions-maven-release/blob/master/release.sh#L64, it does use the maven arguments but as `-Darguments="$MAVEN_ARGS"`
Perhaps I could create a new one called $MAVEN_OPTIONS that you could pass along the maven command

**Comment by qcastel** [comment]
this feature should solve the problem: https://github.com/qcastel/github-actions-maven-release#adding-maven-options

If you are still facing the issue, don't hesitate to re-open this ticket.
