### ISSUE TITLE
Default configuration does not work?

### ISSUE THREAD

**Issue by sunsear** [qcastel/github-actions-maven-release#9]
I tried using the default configuration and even before changing anything, I get a validation error:

![Schermafbeelding 2020-08-27 om 16 29 37](https://user-images.githubusercontent.com/2803378/91455688-b0556380-e882-11ea-953e-fa6d9f8b4d85.png)

Is something wrong with my config?

**Comment by qcastel** [comment]
Hello @sunsear,

I recently did use this maven plugin on the following repo. https://github.com/yapily/jose-database/blob/master/.github/workflows/release.yaml#L34
Perhaps this could be a good base for your project.

**Comment by sunsear** [comment]
Ah, that does provide some insight! I thought it would have to be toplevel in the YML. I will investigate what happens if I put it as one of the actions.

**Comment by qcastel** [comment]
@sunsear I haven't heard from you since. I would assume you managed to workaround your issue.
If not feel free to re-open this issue!

**Comment by sunsear** [comment]
Sorry, forgot to update you. The project that we are working on is to be a part of ImageJ and they have a travis setup that they would like us to use. Haven't been able to spend any time on this anymore therefore. Closing is fine with me!
